- name: install python2 on ubuntu 18.04 instances
  hosts: "*"
  gather_facts: false
  tasks:
    - name: run apt-get update , install python, git and  openssh-server
      raw: "{{ item }}"
      loop:
        - sudo apt-get update
        - sudo apt-get -y install git 
        - sudo apt-get -y install python
        - sudo apt-get -y install openssh-server
      become: true

- name: misc task on ubuntu 18.04 instance
  hosts: "*"
  tasks:
    - debug: var=ansible_host
